#!/bin/bash

echo "This script installs oh-my-zsh, tmuxifier, rbenv, and updates z.sh"
echo "and any other .dotfile git submodules"
read -p "Are you certain you want to do this? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
  read -p "Start ssh-agent? (y/n) " -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]
  then
    eval $(ssh-agent)
    ssh-add
  fi

  read -p "Update .dotfile submodules? (y/n) " -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]
  then
    cd ~/.dotfiles || exit
    git submodule update --init --recursive
  fi
fi
