#!/bin/bash

echo "This script installs some very useful basic packages on both linux and macOS"

unameOut="$(uname -s)"
case "${unameOut}" in
  Linux*)     machine=Linux;;
  Darwin*)    machine=Mac;;
  CYGWIN*)    machine=Cygwin;;
  MINGW*)     machine=MinGw;;
  *)          machine="UNKNOWN:${unameOut}"
esac
echo ${machine}

case $machine in
  Mac)
    update_command="brew update"
    install_command="brew install"
    clean_command="brew cleanup"
    ;;
  Linux)
    update_command="sudo apt-get -qq update"
    install_command="sudo apt-get install -yqq"
    clean_command="sudo apt-get autoclean"
    ;;
  *)
    update_command="#"
    install_command="#"
    clean_command="#"
esac


echo "Installing with $install_command"

# For all these packages, both brew and apt-get have the same name

# git ca-certificates curl openssh-client and zsh needed for oh-my-zsh
# installation
# make needed for dotfile installations
declare -a packages=(
  "git"
  "ca-certificates"
  "curl"
  "openssh-client"
  "zsh"
  "make"
  "cmake"
  "grep"
  "neofetch"
  "neovim"
  "sudo"
  "tmux"
  "gh"
)

eval "$update_command"

for package in "${packages[@]}"

do
    echo "Installing ${package}"
    eval "$install_command $package"
done

eval "$clean_command"

# Ensure Homebrew is installed everywhere, it's useful
case $machine in
  Mac)
    # Check for Homebrew,
    # Install if we don't have it
    if test ! $(which brew); then
      echo "Installing homebrew..."
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi
    ;;
  Linux)
    # Check for Homebrew,
    # Install if we don't have it
    if test ! $(which brew); then
      echo "Installing homebrew..."
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> $HOME/.zprofile
      eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

      sudo apt-get update -qq
      sudo apt-get install -yqq build-essential
    fi

    # Add github package source
    curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
    ;;
  *)
    # no-op
esac

chsh -s /usr/bin/zsh


