#!/bin/bash

echo "This script installs a full dev environment and tools"
read -p "Are you certain you want to do this? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
  read -p "Start ssh-agent? (y/n) " -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]
  then
    eval $(ssh-agent)
    ssh-add
  fi

  # Add common projects and dirs
  mkdir -p ~/dev/bw/projects/
  mkdir -p ~/notes/
  gh repo clone MEHColeman/just_dev_things.git ~/notes/general

  # Install vim-plug and add plugins
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

  nvim +PlugInstall +qall
  cd $HOME/.dotfiles/vim/plugged/YouCompleteMe || exit
  ./install.py --all

  read -p "Install uctags? (y/n) " -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]
  then
    curl https://raw.githubusercontent.com/universal-ctags/ctags-docker/master/uctags > /usr/local/bin/uctags
    chmod +x /usr/local/bin/uctags
  fi

  read -p "Install rbenv? (y/n) " -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]
  then
    curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash
  fi
fi
