#!/bin/sh

# Update homebrew recipes
brew update

# Install GNU core utilities (those that come with OS X are outdated)
brew install coreutils

# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
brew install findutils

# Install Bash 4
brew install bash

# Install more recent versions of some OS X tools
brew tap homebrew/dupes
brew install homebrew/dupes/grep

binaries=(
  "cmake"
  "ctags"
  "diffr"
  "erlang"
  "elixir"
  "mosh"
  "pyqt"
  "qt"
  "rbenv"
  "reattach-to-user-namespace"
  "ruby-build"
  "sip"
  "zsh-syntax-highlighting"
)

echo "installing binaries..."
brew install "${binaries[@]}"

brew cleanup

# Apps
apps=(
  "alacritty"
  "balenaetcher"
  "lastpass"
)

# Install apps to /Applications
# Default is: /Users/$user/Applications
echo "installing apps..."
brew cask install --appdir="/Applications" "${apps[@]}"

echo "Don't forget to remove the ctrl-arrow mac shortcuts so that tmux works nicely"
