#!/bin/bash

sudo apt-get update

declare -a binaries=(
  "coreutils"
  "findutils"
  "exuberant-ctags"
  "erlang"
  "elixir"
  "ruby-build"
  "zsh-syntax-highlighting"
)

echo "installing binaries..."
sudo apt-get install -yqq "${binaries[@]}"
