#!/bin/sh
# copied from lapwinglabs,com/blog/hacker-guide-to-setting-up-your-mac

sudo apt-get update

declare -a binaries=(
  "coreutils"
  "findutils"
  "ctags"
  "diffr"
  "erlang"
  "elixir"
  "pyqt"
  "qt"
  "ruby-build"
  "sip"
  "zsh-syntax-highlighting"
)

echo "installing binaries..."
sudo apt-get install -yqq "${binaries[@]}"
