#!/bin/bash

echo "This script installs various useful packages on both linux and macOS"

unameOut="$(uname -s)"
case "${unameOut}" in
  Linux*)     machine=Linux;;
  Darwin*)    machine=Mac;;
  CYGWIN*)    machine=Cygwin;;
  MINGW*)     machine=MinGw;;
  *)          machine="UNKNOWN:${unameOut}"
esac
echo ${machine}

case $machine in
  Mac)
    update_command="brew update"
    install_command="brew install"
    clean_command="brew cleanup"
    brew_tap_command="brew tap homebrew/cask-"
    brew_cask_command="brew install --cask"
    ;;
  Linux)
    update_command="sudo apt-get -qq update"
    install_command="sudo apt-get install -yqq"
    clean_command="sudo apt-get autoclean"
    brew_tap_command="brew tap linuxbrew/"
    brew_cask_command="brew install --HEAD"
    ;;
  *)
    update_command="#"
    install_command="#"
    clean_command="#"
esac

echo "Installing with $install_command"

# both brew and apt-get have the same name
declare -a packages=(
  "ack"
  "alacritty"
  "bash"
  "coreutils"
  "dfu-util"
  "elixir"
  "findutils"
  "gcc"
  "glances"
  "hadolint"
  "mosh"
  "node"
  "par"
  "postgresql"
  "rbenv"
  "shellcheck"
  "thefuck"
  "tig"
  "tree"
  "vagrant"
)

eval "$update_command"

# You need this to install alacritty on linux, via apt-get
if [[ $machine=Linux ]]
then
  sudo apt-get install -yqq software-properties-common
  sudo add-apt-repository ppa:aslatter/ppa
  wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
  echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
fi

for package in "${packages[@]}"

do
  echo "Installing ${package}"
  eval $install_command $package
done

brew install mcfly
brew install diffr

eval ${brew_tap_command}fonts

fonts=(
  font-mplus
  font-clear-sans
  font-inconsolata
  font-rosario
  font-roboto
)

# install fonts
echo "installing fonts..."
eval $brew_cask_command "${fonts[@]}"

eval "$clean_command"

echo "Done"
