#!/bin/bash

echo "This script installs various useful packages on both linux and macOS"

unameOut="$(uname -s)"
case "${unameOut}" in
  Linux*)     machine=Linux;;
  Darwin*)    machine=Mac;;
  CYGWIN*)    machine=Cygwin;;
  MINGW*)     machine=MinGw;;
  *)          machine="UNKNOWN:${unameOut}"
esac
echo ${machine}

case $machine in
  Mac)
    update_command="brew update"
    install_command="brew install"
    clean_command="brew clean"
    ;;
  Linux)
    update_command="apt-get -qq update"
    install_command="apt-get install -yqq"
    clean_command="apt-get autoclean"
    ;;
  *)
    update_command="#"
    install_command="#"
    clean_command="#"
esac

echo "Installing with $install_command"

# both brew and apt-get have the same name
declare -a packages=(
  "ack"
  "alacritty"
  "bash"
  "coreutils"
  "dfu-util"
  "elixir"
  "findutils"
  "gcc"
  "glances"
  "hadolint"
  "mosh"
  "node"
  "obsidian"
  "par"
  "postgresql"
  "rbenv"
  "shellcheck"
  "thefuck"
  "tig"
  "tree"
)

eval "$update_command"

# You need this to install alacritty on linux, via apt-get
if [[ $machine=Linux ]]
then
  apt-get install software-properties-common
  add-apt-repository ppa:aslatter/ppa
fi

for package in "${packages[@]}"

do
  read -p "Install ${package} ? (y/n) " -n 1 -r
  if [[ $REPLY =~ ^[Yy]$ ]]
  then
    echo "Installing ${package}"
    eval $install_command $package
  fi
done

brew install mcfly

brew tap caskroom/fonts
fonts=(
  font-m-plus
  font-clear-sans
  font-roboto
  font-inconsolata
  font-rosario
)

# install fonts
echo "installing fonts..."
brew cask install "${fonts[@]}"


eval "$clean_command"

echo "Done"
